<?php

/**
 * @file
 * Contains serc_updater.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_system_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the serc_updater module.
    case 'help.page.block_system':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function block_system_cron() {
  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');

  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('block_system');

  // Do not fill the queue while there are still unprocessed items.
  if (!$queue->numberOfItems()) {
    /** @var EntityStorageInterface $storage */
    $storage = \Drupal::service('entity.manager')->getStorage('block_content');

    $ids = array_keys($storage->loadByProperties(['type' => 'stock_exchange_rate_card']));
    foreach ($ids as $id) {
      $queue->createItem($id);
    }
  }
}
