<?php

/**
 * @file
 * Contains block_system.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

function block_system_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the serc_updater module.
    case 'help.page.block_system':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
function block_system_cron() {

  $queue_factory = \Drupal::service('queue');


  $queue = $queue_factory->get('block_system');


  if (!$queue->numberOfItems()) {
  
    $storage = \Drupal::service('entity.manager')->getStorage('block_content');

    $ids = array_keys($storage->loadByProperties(['type' => 'stock_exchange_rate_card']));
    foreach ($ids as $id) {
      $queue->createItem($id);
    }
  }
}
